### PR TITLE
docs: combine GitHub Actions docs

### LINKED ISSUE #907: GH actions docs inconsistency
1. The GH Action pages are duplicated:
- https://python-semantic-release.readthedocs.io/en/latest/github-action.html
- https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html

3. [The action does not run `version` and `publish` per documentation](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html). It runs only `version`, at least that's what I see from:
https://github.com/python-semantic-release/python-semantic-release/blob/master/action.sh#L97

(and yes, it should stay this way or it there should be a flag to disable publishing for non PyPi builds).

### PR DESCRIPTION
**Pull request by wyardley**
## Purpose

- Combine all the GitHub Actions details into a single location in the documentation
- Resolve #907

## Rationale

Having two separate docs with similar filenames for GitHub Actions (one for the action itself, and one on configuring it for automatic release) is a little confusing (see linked ticket).

## How did you test?

Visual inspection in the browser

## How to Verify

```sh
sphinx-autobuild --open-browser docs docs/_build/html
```

### CODE REVIEW

**Comment by wyardley** [comment]
Oh and need to update the version bump - I’ll do that in a second.

**Comment by codejedi365** [comment]
When you say visually inspected, did you use the `sphinx-autobuild` to see how it was formatted?

**Comment by wyardley** [comment]
> When you say visually inspected, did you use the sphinx-autobuild to see how it was formatted?

No, I just previewed in GH, but I'll do that, and fix the warnings / update references.

**Comment by wyardley** [comment]
Don't see any glaring issues now, but let me know what you think, as well as what you think of the order / layout.
I left the outputs formatted as a table, but left everything else in its original format, and just added another level of titles above the inputs.

**Comment by codejedi365** [comment]
> No, I just previewed in GH, but I'll do that, and fix the warnings / update references.

See the contributors doc for command usage if needed.  Try to keep each PR contained so only worry about the warnings related to the part you are changing. we will do the other errors separately or whenever I get around to it.

**Comment by codejedi365** [comment]
I'll take a look shortly

**Review by codejedi365 — APPROVED** [review]
@wyardley, this is great work! Thank you for putting in the time. I'm going to add some wording adjustments on top (just my preferences) and hopefully merge it today.

I have added more "good first issue" tags and there are also the "needs-docs" labels if you would rather do documentation changes.

**Comment by wyardley** [comment]
Thanks. @codejedi365 do you want me to look over the changes, or you'll just merge when you get a chance. The updates seem fine to me.

**Comment by codejedi365** [comment]
I'll just merge them, no problem, thanks. Sorry, I've caught Covid in the last few days so I haven't done much of anything since the weekend

**Comment by wyardley** [comment]
Yikes! Feel better 😷

**Comment by codejedi365** [comment]
@wyardley, would you give this a review in the browser in case I missed something (like a link or copy/paste description error). I definitely went overboard with styling (alphabetical inputs/outputs, headings, etc.) and adding a lot more depth to the descriptions and examples.  Thank you for giving me the starting point!

**Comment by wyardley** [comment]
Looks really nice... LGTM!

>  I would like to change it over to python-semantic-release-publish as the title which is why the docs spell that out instead.

Got it, yes, I noticed the broken link to
https://github.com/marketplace/actions/python-semantic-release-publish vs https://github.com/marketplace/actions/python-semantic-release

I would say that having it have the same name as the GH project seems like a good idea to me, unless you anticipate needing the existing name for something else? Or is that a second / different action (for `upload-to-gh-release`)?

**Comment by codejedi365** [comment]
Yep, that's the link, it will exist after a marketplace publish.

> I would say that having it have the same name as the GH project seems like a good idea to me, unless you anticipate needing the existing name for something else? Or is that a second / different action (for `upload-to-gh-release`)?

I'm not sure I can change the repo name of `upload-to-gh-release` but I'll try. I wanted to just define the sub command of what is actually being called inside the action as a part of the action name. I feel it's more intuitive that way. The action name is just defined in the `action.yml` so I need to update that file first before I start publishing the second action.

**Comment by wyardley** [comment]
> I'm not sure I can change the repo name of upload-to-gh-release

Ooohhh! I didn't realize it was a different repo. Nevermind!
Yeah, if it could be a separate command in the same repo and same action, that would be one thing, but I get what you mean now.

**Comment by codejedi365** [comment]
UPDATE: I have completed the rename/deprecate & release process for the `upload-to-gh-release` to `publish-action` actions.  This included updating both readmes and adding some deprecation messages. I needed to trigger a release here as well to make sure that all actions stayed inline with the same version.  The publish-action is also now published to the marketplace officially and this PR now has all the links matching the new variant.

**Comment by wyardley** [comment]
Woot! Great. Sorry to make work for you instead of saving you work, but I think this will all be really helpful to users of the program.

**Comment by codejedi365** [comment]
Not a problem. I really wish the docs were more thorough and this was a moment of opportunity, and really its most necessary for newcomers that the docs are accurate and detailed. When I find discrepancies or un-intuitive items, I need to address it right away. Ultimately, it also saves me from more open issues in the future.

**Pull request merged**
